version: '5.2.0'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/desafiodb
      - PORT=3000
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
  

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: desafiodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: